language: cpp
# dist: trusty # use gcc 4.8 on linux, but it is not compatible with PDFium
dist: Xenial # use gcc 5.4 on linux
os:
    - linux
    - osx

notifications:
  email:
    on_success: never # default: change
    on_failure: always # default: always


before_install:
    - if [ `uname` = "Linux" ]; then
        sudo apt-get update -qq -y;
        sudo apt-get install curl python perl -y;
      fi

script:
    - ./ci-build/build.sh
