language: cpp
os:
    - linux
    - osx

# dist: trusty # use gcc 4.8 on linux, but it is not compatible with PDFium
dist: bionic # use gcc 9.3.0 on linux
osx_image: xcode11.3

notifications:
  email:
    on_success: never # default: change
    on_failure: always # default: always


before_install:
    - if [ `uname` = "Linux" ]; then
        sudo apt-get update -qq -y;
        sudo apt-get install curl python perl -y;
        sudo apt-get install pkg-config libglib2.0-dev -y;
        sudo apt-get install software-properties-common -y;
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y;
        sudo apt-get update;
        sudo apt-get install gcc-9 g++-9 -y;
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 60;
        sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-9 60;
      fi

script:
    - ./ci-build/build.sh
